apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/application.yaml
    target:
      kind: Application
  - path: patches/overlay-cm.yaml
    target:
      kind: ConfigMap
      name: projects-apps-overlay
replacements:
  - path: replacements/application-overlay-replacement.yaml
