source:
  kind: ConfigMap
  name: projects-apps-overlay
  fieldPath: data.path
targets:
  - select:
      kind: Application
    fieldPaths:
      - spec.source.path
    options:
      delimiter: /
      index: 1
